Repository jumppad-labs/jumppad, pull requests merged in 2024-04, with the labels that each got.

#288 Add GPU resources
  ChangeLog.md
  cmd/changelog.go
  pkg/clients/container/docker_tasks.go
  pkg/clients/container/docker_tasks_container_create_test.go
  pkg/clients/container/types/types.go
  pkg/config/resources/container/provider.go
  pkg/config/resources/container/provider_test.go
  pkg/config/resources/container/resource_container.go
Labels: patch

#290 Add GPU resources for containers and output variables for exec
  ChangeLog.md
  cmd/changelog.go
  cmd/down.go
  cmd/plugin_build.go
  examples/exec/local.hcl
  examples/exec/remote.hcl
  pkg/clients/command/command.go
  pkg/clients/container/docker_tasks.go
  pkg/config/resources/container/provider.go
  pkg/config/resources/exec/provider.go
  pkg/config/resources/exec/provider_test.go
  pkg/config/resources/exec/resource.go
Labels: enhancement, patch

#291 remove dagger cloud
  .github/workflows/build_and_deploy.yaml
Labels: patch

#254 Add the capability to the copy resource to copy from remote sources
  .github/workflows/build_and_deploy.yaml
  README.md
  examples/copy/files/foo
  examples/copy/main.hcl
  examples/copy/test/copy.feature
  pkg/config/functions.go
  pkg/config/resources/copy/provider.go
  pkg/config/resources/copy/resource.go
  pkg/config/resources/copy/resource_test.go
  pkg/config/zz_hclparser.go
Labels: minor

#292 update vulnerable Go dependencies
  go.mod
  go.sum
Labels: enhancement

#293 Update README.md
  README.md
Labels: patch
