Repository jumppad-labs/jumppad, pull requests merged in 2025-03, with the labels that each got.

#324 Update HCLConfig to v0.28.0
  Makefile
  go.mod
  go.sum
Labels: minor

#325 only create default network is no network is defined
  pkg/jumppad/engine.go
  pkg/jumppad/engine_test.go
Labels: patch

#340 add validate command to validate configuration
  .vscode/launch.json
  cmd/root.go
  cmd/validate.go
Labels: ux

#255 HTTP resource
  examples/http/main.hcl
  pkg/config/resources/http/provider.go
  pkg/config/resources/http/provider_test.go
  pkg/config/resources/http/resource.go
  pkg/jumppad/init.go
Labels: enhancement, provider, patch
